### ISSUE TITLE
Is there a way to get speech and sound effects working?

### ISSUE THREAD

**Issue by 60fpshacksrock** [SockNastre/BethesdaSoftworksArchive-OblivionPS3#2]
I was wondering if you could add support to convert voices and sound effects to play on PS3.

The audio player I use, foobar2000, along with plugins like vgmstream which includes ffmpeg detects the audio as:

Filename: amb_firelarge_lp_01.wav

Duration : 0:02.860 (63 054 samples)
Sample rate : 22050 Hz
Channels : 1
Bits per sample : 4
Bitrate : 89 kbps
Codec : IMA ADPCM
Encoding : lossy

Since foobar2000 accepts cmd line encoders I used ffmpeg and converted a sound effect from a lighsaber mod to IMA but no sound would play.

**Comment by SockNastre** [comment]
I have no plans on adding support for voice and audio conversions. There could be many factors into why your conversion failed and did not load, but replicating the audio format as ffmpeg describes it and then making sure file name extensions are correct (WAV, I believe?) is likely crucial to getting something to work; other than this I cannot provide a suitable explanation as to why things didn't work with your process, I wish you luck.

Thank you.
